---
title: "ESM 204 Homework 1"
author: "Justine Lang"
date: "2023-04-06"
output: 
  html_document: 
    code_folding: hide
---

```{r setup, include=FALSE, echo = TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(pracma)
```


### 1. Basics of R

**a.** 

```{r}
seq(0, 10, by = 0.5)
```


**b.**

```{r}
test_fun <- function(X, a, b) {
  return(Y = a*X + b)
}
```

```{r}
test_fun(X = 5, b = 10, a = 3)
```


**c.**

```{r}
test_df <- data.frame(a = c(3),
                 b = c(10),
                 X = c(1:10))

test_df$Y = test_fun(a = test_df$a, b = test_df$b, X = test_df$X)
```

```{r}
test_df
```



**d.**

```{r}
test_gg <- ggplot(data = test_df, aes(x = X, y = Y)) +
  geom_point() +
  theme_minimal()

test_gg
```



**e.**

```{r}
F1 <- function(X, a1, b1) {
  return(Y = a1*X + b1)
}

F2 <- function(X, a2, b2) {
  return(Y = a2*X + b2)
}
```

```{r}
F3 <- function(X, a1, b1, a2, b2) {
  Z = F1(X, a1, b1) - F2(X, a2, b2)
  return(Z)
}
```

```{r}
fzero(fun = F3, x = 7, a1 = -2, b1 = 100, a2 = 3, b2 = 0)

```



**f.**

$-2x + 100 = 3x + 0$

$100 = 5x$

$x = 20$

$y = 3(20) = 60$




### 2. Food Bank Markets

**a.**

[Copy over calculations]


**b**

[Copy over calculations]




### 3. More Complicated Supply and Demand Problems

**a.**

```{r}
### Write functions

car_supply <- function(Q) {
  P = 120 + (0.3*(Q^1.3))
  return(P)
}

car_demand <- function(Q) {
  P = 1000 - Q*0
  return(P)
}
```



**i.**

If P* is 1000, we can rearrange the equation to find Q*. 

```{r}
q_star <- function(P) {
  Q = ((P - 120) / 0.3)^(1/1.3)
  return(Q)
}
```

```{r}
q_star(P = 1000)
```



**ii.**

```{r}
elast <- function(Q1, Q2, P1, P2) {
  E = ((Q2 - Q1)/Q1) / ((P2 - P1)/P1)
  return(E)
}
```

```{r}
# q_star(P = 1500) ### = 656.9102

elast(Q1 = 464.7304, Q2 = 656.9102, P1 = 1000, P2 = 1500)
```



**iii.**

```{r}
### Producer surplus

integral(car_demand, xmin=0, xmax=464.7304) - integral(car_supply, xmin=0, xmax=464.7304)
```



**iv.**

```{r}
### Cost?

1000 * 464.7304 
```


**b.**

**i.**

```{r}
car_mb <- function(Q) {
  P = 1500 - (0.4*(Q^1.2))
  return(P)
}
```

```{r}
f_diff <- function(Q) {
  Z = car_mb(Q) - car_supply(Q)
  return(Z)
}
```

```{r}
# fzero(fun = f_diff, x = 7)$x

### Q = 431.524
```



**ii.**

```{r}
car_mb(431.524)
```












